# GitHub Pages Configuration

# Site settings
title: Longevity Coach
description: AI-Powered Health Optimization Platform
baseurl: "/longevitycoach" # the subpath of your site, e.g. /blog
url: "https://ma3u.github.io" # the base hostname & protocol for your site

theme: jekyll-theme-cayman

# GitHub metadata
github:
  repository_nwo: ma3u/longevitycoach
  build_revision: $GITHUB_SHA
  environment: github-pages

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .github
  - docs/presentation

# Custom variables
description: >-
  Transform your health with AI-powered blood biomarker analysis and personalized longevity guidance.
  Bridge the gap between 'normal' and 'optimal' health with data-driven insights.
