name: Memory Bank Sync

on:
  push:
    branches: [main, master]
    paths:
      - 'memory-bank/**'
  pull_request:
    branches: [main, master]
    paths:
      - 'memory-bank/**'
  workflow_dispatch:

jobs:
  sync-memory-bank:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Validate memory bank files
      run: |
        # Check for required memory bank files
        [ -f memory-bank/activeContext.md ] || exit 1
        [ -f memory-bank/decisionLog.md ] || exit 1
        [ -f memory-bank/progress.md ] || exit 1
        [ -f memory-bank/projectContext.md ] || exit 1
        [ -f memory-bank/systemPatterns.md ] || exit 1
        
        # Check file sizes (max 1MB each)
        find memory-bank -name "*.md" -size +1M | grep . && exit 1 || exit 0
        
    - name: Create summary
      run: |
        echo "# Memory Bank Summary" > memory-summary.md
        echo "Updated: $(date)" >> memory-summary.md
        echo "" >> memory-summary.md
        
        echo "## Recent Changes" >> memory-summary.md
        git log -n 3 --pretty=format:'- %s' -- memory-bank/ >> memory-summary.md
        
    - name: Upload summary
      uses: actions/upload-artifact@v3
      with:
        name: memory-bank-summary
        path: memory-summary.md
        retention-days: 5
