name: Validate Documentation

on:
  push:
    branches: [main, master]
    paths:
      - '**/*.md'
      - '!node_modules/**'
      - '.github/workflows/validate-docs.yml'
  pull_request:
    branches: [main, master]
    paths:
      - '**/*.md'
      - '!node_modules/**'
      - '.github/workflows/validate-docs.yml'
  workflow_dispatch:

jobs:
  validate-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install markdownlint
      run: |
        npm install -g markdownlint-cli
        npm install -g markdownlint-cli2
    
    - name: Validate Markdown files
      run: |
        # Check all markdown files except node_modules
        find . -name "*.md" -not -path "*/node_modules/*" -print0 | xargs -0 markdownlint -c .markdownlint.json --disable MD013 --disable MD033
    
    - name: Validate ADR format
      run: |
        # Check that all ADRs have required sections
        for file in memory-bank/decisions/*.md; do
          if [ -f "$file" ]; then
            if ! grep -q '^## Status$' "$file" || \
               ! grep -q '^## Context$' "$file" || \
               ! grep -q '^## Decision$' "$file" || \
               ! grep -q '^## Consequences$' "$file"; then
              echo "::error file=$file::ADR is missing required sections (Status, Context, Decision, Consequences)"
              exit 1
            fi
          fi
        done
    
    - name: Check for broken links
      run: |
        # Simple link checking for internal links
        find memory-bank -name "*.md" -exec grep -o '\[[^]]*\]([^)]*)' {} \; | \
          grep -v 'http' | \
          sed -E 's/.*\(([^)]+)\).*/\1/' | \
          while read -r link; do
            if [[ ! -f "memory-bank/$link" ]] && [[ ! -f "$link" ]]; then
              echo "::error::Broken link found: $link"
              exit 1
            fi
          done
